### PR TITLE
ensures readme instruction consistency

### PR DESCRIPTION
**Pull request by tansaku**
to be same as with all other challenges in instruction section

### CODE REVIEW

**Comment by silvabox** [comment]
hello

**Comment by makers-dev** [comment]
hello again

**Comment by makers-dev** [comment]
You had your rps-challenge reviewed by **yourname**

### The good points are:

* readmeshouldhavescreenshotsandinstructionsonhowtouseapplication
* nottestingallofthegamelogicinunittests
* testingtoomuchgamelogicinfeaturetests
* useofifelsifconditionalsforbusinesslogic
* notencapsulatingthecomputerinaseparateclass
* inconsistentfolderlayoutsinatrastructure
* inconsistentfilenaming
* callingbusinesslogicfromtheview

### You should consider the following improvements:

* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Use of global variables
* Not storing the weapons in a constant
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Fat Controllers

### Additional comments:
anyadditionalcommentsonthecodeyoureviewed

see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by makers-dev** [comment]
You had your rps-challenge reviewed by **yourname**

### The good points are:

* readmeshouldhavescreenshotsandinstructionsonhowtouseapplication
* nottestingallofthegamelogicinunittests
* testingtoomuchgamelogicinfeaturetests
* useofifelsifconditionalsforbusinesslogic
* notencapsulatingthecomputerinaseparateclass
* inconsistentfolderlayoutsinatrastructure
* inconsistentfilenaming
* callingbusinesslogicfromtheview

### You should consider the following improvements:

* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Use of global variables
* Not storing the weapons in a constant
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Fat Controllers

### Additional comments:
anyadditionalcommentsonthecodeyoureviewed

see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by makers-dev** [comment]
You had your rps-challenge reviewed by **yourname**

### The good points are:

* readmeshouldhavescreenshotsandinstructionsonhowtouseapplication
* nottestingallofthegamelogicinunittests
* testingtoomuchgamelogicinfeaturetests
* useofifelsifconditionalsforbusinesslogic
* notencapsulatingthecomputerinaseparateclass
* inconsistentfolderlayoutsinatrastructure
* inconsistentfilenaming
* callingbusinesslogicfromtheview

### You should consider the following improvements:

* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Use of global variables
* Not storing the weapons in a constant
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Fat Controllers

### Additional comments:
anyadditionalcommentsonthecodeyoureviewed

see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by makers-dev** [comment]
You had your rps-challenge reviewed by **yourname**

### The good points are:

* readmeshouldhavescreenshotsandinstructionsonhowtouseapplication
* nottestingallofthegamelogicinunittests
* testingtoomuchgamelogicinfeaturetests
* useofifelsifconditionalsforbusinesslogic
* notencapsulatingthecomputerinaseparateclass
* inconsistentfolderlayoutsinatrastructure
* inconsistentfilenaming
* callingbusinesslogicfromtheview

### You should consider the following improvements:

* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Use of global variables
* Not storing the weapons in a constant
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Fat Controllers

### Additional comments:
anyadditionalcommentsonthecodeyoureviewed

see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by makers-dev** [comment]
You had your rps-challenge reviewed by **yourname**

### The good points are:

* readmeshouldhavescreenshotsandinstructionsonhowtouseapplication
* nottestingallofthegamelogicinunittests
* testingtoomuchgamelogicinfeaturetests
* useofifelsifconditionalsforbusinesslogic
* notencapsulatingthecomputerinaseparateclass
* inconsistentfolderlayoutsinatrastructure
* inconsistentfilenaming
* callingbusinesslogicfromtheview

### You should consider the following improvements:

* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Use of global variables
* Not storing the weapons in a constant
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Fat Controllers

### Additional comments:
anyadditionalcommentsonthecodeyoureviewed

see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by makers-dev** [comment]
You had your rps-challenge reviewed by **yourname**

### The good points are:

* readmeshouldhavescreenshotsandinstructionsonhowtouseapplication
* nottestingallofthegamelogicinunittests
* testingtoomuchgamelogicinfeaturetests
* useofifelsifconditionalsforbusinesslogic
* notencapsulatingthecomputerinaseparateclass
* inconsistentfolderlayoutsinatrastructure
* inconsistentfilenaming
* callingbusinesslogicfromtheview

### You should consider the following improvements:

* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Use of global variables
* Not storing the weapons in a constant
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Fat Controllers

### Additional comments:
anyadditionalcommentsonthecodeyoureviewed

see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by makers-dev** [comment]
You had your rps-challenge reviewed by ****

### The good points are:


### You should consider the following improvements:

* README should have screenshots and instructions on how to use application
* Not testing all of the game logic in unit tests
* Testing too much game logic in feature tests
* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Use of if/elsif conditionals for business logic
* Not encapsulating the 'computer' in a separate class
* Use of global variables
* Not storing the weapons in a constant
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Inconsistent folder layout (Sinatra structure)
* Inconsistent file naming
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Calling business logic from the view
* Fat Controllers


see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by makers-dev** [comment]
You had your rps-challenge reviewed by ****

### The good points are:


### You should consider the following improvements:

* README should have screenshots and instructions on how to use application
* Not testing all of the game logic in unit tests
* Testing too much game logic in feature tests
* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Use of if/elsif conditionals for business logic
* Not encapsulating the 'computer' in a separate class
* Use of global variables
* Not storing the weapons in a constant
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Inconsistent folder layout (Sinatra structure)
* Inconsistent file naming
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Calling business logic from the view
* Fat Controllers


see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by student-progress-tracker-dev** [comment]
You had your rps-challenge reviewed by **Jongmin Kim**

### The good points are:


### You should consider the following improvements:

* README should have screenshots and instructions on how to use application
* Not testing all of the game logic in unit tests
* Testing too much game logic in feature tests
* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Use of if/elsif conditionals for business logic
* Not encapsulating the 'computer' in a separate class
* Use of global variables
* Not storing the weapons in a constant
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Inconsistent folder layout (Sinatra structure)
* Inconsistent file naming
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Calling business logic from the view
* Fat Controllers


see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by student-progress-tracker-dev** [comment]
You had your rps-challenge reviewed by **dan**

### The good points are:

* Every possible outcome of the game logic is tested at the unit level
* The feature tests test a reasonable subset of game logic
* long if/elsif conditionals avoided in business logic
* Business and presentation logic has been cleanly separated
* No global variables used
* Routes consistently named, Routes use of POST and GET is consistent
* The file structure followed recognizable conventions
* files and classes are named consistently
* There is no commented code
* The code minimizes the amout of business logic in the view

### You should consider the following improvements:

* README should have screenshots and instructions on how to use application
* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Not storing the weapons in a constant
* Defining weapons in more than one place
* Not initializing capybara/ spec_helper correctly
* Random behaviour not stubbed out at feature level
* Fat Controllers


see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by student-progress-tracker-dev** [comment]
You had your rps-challenge reviewed by **dan**

### The good points are:

* Every possible outcome of the game logic is tested at the unit level
* The feature tests test a reasonable subset of game logic
* long if/elsif conditionals avoided in business logic
* Business and presentation logic has been cleanly separated
* No global variables used
* Routes consistently named, Routes use of POST and GET is consistent
* The file structure followed recognizable conventions
* files and classes are named consistently
* There is no commented code
* The code minimizes the amout of business logic in the view

### You should consider the following improvements:

* README should have screenshots and instructions on how to use application
* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Not storing the weapons in a constant
* Defining weapons in more than one place
* Not initializing capybara/ spec_helper correctly
* Random behaviour not stubbed out at feature level
* Fat Controllers


see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by makers-dev** [comment]
You had your rps-challenge reviewed by ****

### The good points are:


### You should consider the following improvements:

* README should have screenshots and instructions on how to use application
* Not testing all of the game logic in unit tests
* Testing too much game logic in feature tests
* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Use of if/elsif conditionals for business logic
* Not encapsulating the 'computer' in a separate class
* Use of global variables
* Not storing the weapons in a constant
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Inconsistent folder layout (Sinatra structure)
* Inconsistent file naming
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Calling business logic from the view
* Fat Controllers


see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by student-progress-tracker-dev** [comment]
You had your rps-challenge reviewed by ****

### The good points are:


### You should consider the following improvements:

* README should have screenshots and instructions on how to use application
* Not testing all of the game logic in unit tests
* Testing too much game logic in feature tests
* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Use of if/elsif conditionals for business logic
* Not encapsulating the 'computer' in a separate class
* Use of global variables
* Not storing the weapons in a constant
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Inconsistent folder layout (Sinatra structure)
* Inconsistent file naming
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Calling business logic from the view
* Fat Controllers


see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by student-progress-tracker-dev** [comment]
You had your rps-challenge reviewed by **Yev Dyko**

### The good points are:

* The README has instructions
* Every possible outcome of the game logic is tested at the unit level
* The feature tests test a reasonable subset of game logic
* Win, lose and draw outcomes are all tested at the feature level
* long if/elsif conditionals avoided in business logic
* Business and presentation logic has been cleanly separated
* Routes consistently named, Routes use of POST and GET is consistent
* The file structure followed recognizable conventions
* files and classes are named consistently
* There is no commented code
* The code minimizes the amout of business logic in the view
* The controllers are thin with minimal business logic

### You should consider the following improvements:

* Including presentation strings in business logic layer
* Use of global variables
* Not storing the weapons in a constant
* Defining weapons in more than one place
* Not initializing capybara/ spec_helper correctly
* Random behaviour not stubbed out at feature level

### Additional comments:
Reasonable attempt. Good job!

see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by student-progress-tracker-dev** [comment]
You had your rps-challenge reviewed by **Yev Dyko**

### The good points are:

* The README has instructions
* Every possible outcome of the game logic is tested at the unit level
* The feature tests test a reasonable subset of game logic
* Win, lose and draw outcomes are all tested at the feature level
* long if/elsif conditionals avoided in business logic
* Business and presentation logic has been cleanly separated
* Routes consistently named, Routes use of POST and GET is consistent
* The file structure followed recognizable conventions
* files and classes are named consistently
* There is no commented code
* The code minimizes the amout of business logic in the view
* The controllers are thin with minimal business logic

### You should consider the following improvements:

* Including presentation strings in business logic layer
* Use of global variables
* Not storing the weapons in a constant
* Defining weapons in more than one place
* Not initializing capybara/ spec_helper correctly
* Random behaviour not stubbed out at feature level

### Additional comments:
Reasonable attempt. Good job!

see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by student-progress-tracker-dev** [comment]
You had your rps-challenge reviewed by **Yev Dyko**

### The good points are:

* The README has instructions
* Every possible outcome of the game logic is tested at the unit level
* The feature tests test a reasonable subset of game logic
* Win, lose and draw outcomes are all tested at the feature level
* long if/elsif conditionals avoided in business logic
* Business and presentation logic has been cleanly separated
* Routes consistently named, Routes use of POST and GET is consistent
* The file structure followed recognizable conventions
* files and classes are named consistently
* There is no commented code
* The code minimizes the amout of business logic in the view
* The controllers are thin with minimal business logic

### You should consider the following improvements:

* Including presentation strings in business logic layer
* Use of global variables
* Not storing the weapons in a constant
* Defining weapons in more than one place
* Not initializing capybara/ spec_helper correctly
* Random behaviour not stubbed out at feature level

### Additional comments:
Reasonable attempt. Good job!

see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by makers-dev** [comment]
You had your rps-challenge reviewed by ****

### The good points are:


### You should consider the following improvements:

* README should have screenshots and instructions on how to use application
* Not testing all of the game logic in unit tests
* Testing too much game logic in feature tests
* Not testing all game outcomes in feature tests
* Including presentation strings in business logic layer
* Use of if/elsif conditionals for business logic
* Not encapsulating the 'computer' in a separate class
* Use of global variables
* Not storing the weapons in a constant
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Inconsistent folder layout (Sinatra structure)
* Inconsistent file naming
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Calling business logic from the view
* Fat Controllers


see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by makers-dev** [comment]
You had your rps-challenge reviewed by **Ben**

### The good points are:

* The README has instructions, The README has a screenshot(s)
* The feature tests test a reasonable subset of game logic
* Win, lose and draw outcomes are all tested at the feature level
* No global variables used
* weapons are sensibly stored in a constant
* files and classes are named consistently

### You should consider the following improvements:

* Not testing all of the game logic in unit tests
* Including presentation strings in business logic layer
* Use of if/elsif conditionals for business logic
* Not encapsulating the 'computer' in a separate class
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Inconsistent folder layout (Sinatra structure)
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Calling business logic from the view
* Fat Controllers

### Additional comments:
fun fun fun

see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by makers-dev** [comment]
You had your rps-challenge reviewed by **Ben**

### The good points are:

* The README has instructions, The README has a screenshot(s)
* The feature tests test a reasonable subset of game logic
* Win, lose and draw outcomes are all tested at the feature level
* No global variables used
* weapons are sensibly stored in a constant
* files and classes are named consistently

### You should consider the following improvements:

* Not testing all of the game logic in unit tests
* Including presentation strings in business logic layer
* Use of if/elsif conditionals for business logic
* Not encapsulating the 'computer' in a separate class
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Inconsistent folder layout (Sinatra structure)
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Calling business logic from the view
* Fat Controllers

### Additional comments:
fun fun fun

see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by makers-dev** [comment]
You had your rps-challenge reviewed by **Ben**

### The good points are:

* The README has instructions, The README has a screenshot(s)
* The feature tests test a reasonable subset of game logic
* Win, lose and draw outcomes are all tested at the feature level
* No global variables used
* weapons are sensibly stored in a constant
* files and classes are named consistently

### You should consider the following improvements:

* Not testing all of the game logic in unit tests
* Including presentation strings in business logic layer
* Use of if/elsif conditionals for business logic
* Not encapsulating the 'computer' in a separate class
* Inconsistent routing and route naming
* Defining weapons in more than one place
* Inconsistent folder layout (Sinatra structure)
* Not initializing capybara/ spec_helper correctly
* Not removing comments before committing
* Random behaviour not stubbed out at feature level
* Calling business logic from the view
* Fat Controllers

### Additional comments:
fun fun fun

see https://github.com/makersacademy/rps-challenge/blob/master/docs/review.md for more details

**Comment by tansaku** [comment]
closes #218

**Pull request merged**
